name: release

on:
  release:
    types: [created]

jobs:
  deploy_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker build and push
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: jumo20201124/jumo20201124
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tag_names: true
    - name: docker build and push
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: jumo20201124/jumo20201124
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tags: "latest"


